class CricketExecutor{

    public static void main(String[] args){

        System.out.println(" Default Constructor Objects");

        Cricket ref1=new Cricket();
        ref1.teamName="India";
        ref1.captain="Rohit";
        ref1.coach="Dravid";
        ref1.stadium="Wankhede";
        ref1.country="India";
        ref1.players=11;
        ref1.runs=300;
        ref1.wickets=8;
        ref1.overs=50;
        ref1.matchType="ODI";
        ref1.ranking=1;
        ref1.wins=10;
        ref1.losses=2;
        ref1.draws=0;
        ref1.trophies=5;
        ref1.sponsor="Dream11";
        ref1.jerseyColor="Blue";
        ref1.foundedYear=1928;
        ref1.budget=500;
        ref1.fans=1000000;

        System.out.println(ref1.teamName);
        System.out.println(ref1.captain);
        System.out.println(ref1.coach);
        System.out.println(ref1.stadium);
        System.out.println(ref1.country);
        System.out.println(ref1.players);
        System.out.println(ref1.runs);
        System.out.println(ref1.wickets);
        System.out.println(ref1.overs);
        System.out.println(ref1.matchType);
        System.out.println(ref1.ranking);
        System.out.println(ref1.wins);
        System.out.println(ref1.losses);
        System.out.println(ref1.draws);
        System.out.println(ref1.trophies);
        System.out.println(ref1.sponsor);
        System.out.println(ref1.jerseyColor);
        System.out.println(ref1.foundedYear);
        System.out.println(ref1.budget);
        System.out.println(ref1.fans);
		
		        Cricket ref2=new Cricket();
        ref2.teamName="Australia";
        ref2.captain="Cummins";
        ref2.coach="McDonald";
        ref2.stadium="MCG";
        ref2.country="Australia";
        ref2.players=11;
        ref2.runs=280;
        ref2.wickets=7;
        ref2.overs=50;
        ref2.matchType="ODI";
        ref2.ranking=2;
        ref2.wins=9;
        ref2.losses=3;
        ref2.draws=0;
        ref2.trophies=6;
        ref2.sponsor="Qantas";
        ref2.jerseyColor="Yellow";
        ref2.foundedYear=1905;
        ref2.budget=450;
        ref2.fans=900000;

        System.out.println(ref2.teamName);
        System.out.println(ref2.captain);
        System.out.println(ref2.coach);
        System.out.println(ref2.stadium);
        System.out.println(ref2.country);
        System.out.println(ref2.players);
        System.out.println(ref2.runs);
        System.out.println(ref2.wickets);
        System.out.println(ref2.overs);
        System.out.println(ref2.matchType);
        System.out.println(ref2.ranking);
        System.out.println(ref2.wins);
        System.out.println(ref2.losses);
        System.out.println(ref2.draws);
        System.out.println(ref2.trophies);
        System.out.println(ref2.sponsor);
        System.out.println(ref2.jerseyColor);
        System.out.println(ref2.foundedYear);
        System.out.println(ref2.budget);
        System.out.println(ref2.fans);


        Cricket ref3=new Cricket();
        ref3.teamName="England";
        ref3.captain="Buttler";
        ref3.coach="Mott";
        ref3.stadium="Lords";
        ref3.country="England";
        ref3.players=11;
        ref3.runs=270;
        ref3.wickets=6;
        ref3.overs=50;
        ref3.matchType="ODI";
        ref3.ranking=3;
        ref3.wins=8;
        ref3.losses=4;
        ref3.draws=0;
        ref3.trophies=3;
        ref3.sponsor="Natwest";
        ref3.jerseyColor="Blue";
        ref3.foundedYear=1877;
        ref3.budget=430;
        ref3.fans=850000;

        System.out.println(ref3.teamName);
        System.out.println(ref3.captain);
        System.out.println(ref3.coach);
        System.out.println(ref3.stadium);
        System.out.println(ref3.country);
        System.out.println(ref3.players);
        System.out.println(ref3.runs);
        System.out.println(ref3.wickets);
        System.out.println(ref3.overs);
        System.out.println(ref3.matchType);
        System.out.println(ref3.ranking);
        System.out.println(ref3.wins);
        System.out.println(ref3.losses);
        System.out.println(ref3.draws);
        System.out.println(ref3.trophies);
        System.out.println(ref3.sponsor);
        System.out.println(ref3.jerseyColor);
        System.out.println(ref3.foundedYear);
        System.out.println(ref3.budget);
        System.out.println(ref3.fans);


        Cricket ref4=new Cricket();
        ref4.teamName="Pakistan";
        ref4.captain="Babar";
        ref4.coach="Bradburn";
        ref4.stadium="Gaddafi";
        ref4.country="Pakistan";
        ref4.players=11;
        ref4.runs=260;
        ref4.wickets=9;
        ref4.overs=50;
        ref4.matchType="ODI";
        ref4.ranking=4;
        ref4.wins=7;
        ref4.losses=5;
        ref4.draws=0;
        ref4.trophies=2;
        ref4.sponsor="Pepsi";
        ref4.jerseyColor="Green";
        ref4.foundedYear=1952;
        ref4.budget=410;
        ref4.fans=800000;

        System.out.println(ref4.teamName);
        System.out.println(ref4.captain);
        System.out.println(ref4.coach);
        System.out.println(ref4.stadium);
        System.out.println(ref4.country);
        System.out.println(ref4.players);
        System.out.println(ref4.runs);
        System.out.println(ref4.wickets);
        System.out.println(ref4.overs);
        System.out.println(ref4.matchType);
        System.out.println(ref4.ranking);
        System.out.println(ref4.wins);
        System.out.println(ref4.losses);
        System.out.println(ref4.draws);
        System.out.println(ref4.trophies);
        System.out.println(ref4.sponsor);
        System.out.println(ref4.jerseyColor);
        System.out.println(ref4.foundedYear);
        System.out.println(ref4.budget);
        System.out.println(ref4.fans);


        Cricket ref5=new Cricket();
        ref5.teamName="SouthAfrica";
        ref5.captain="Markram";
        ref5.coach="Boucher";
        ref5.stadium="Newlands";
        ref5.country="SouthAfrica";
        ref5.players=11;
        ref5.runs=250;
        ref5.wickets=8;
        ref5.overs=50;
        ref5.matchType="ODI";
        ref5.ranking=5;
        ref5.wins=6;
        ref5.losses=6;
        ref5.draws=0;
        ref5.trophies=1;
        ref5.sponsor="Castle";
        ref5.jerseyColor="Green";
        ref5.foundedYear=1889;
        ref5.budget=390;
        ref5.fans=750000;

        System.out.println(ref5.teamName);
        System.out.println(ref5.captain);
        System.out.println(ref5.coach);
        System.out.println(ref5.stadium);
        System.out.println(ref5.country);
        System.out.println(ref5.players);
        System.out.println(ref5.runs);
        System.out.println(ref5.wickets);
        System.out.println(ref5.overs);
        System.out.println(ref5.matchType);
        System.out.println(ref5.ranking);
        System.out.println(ref5.wins);
        System.out.println(ref5.losses);
        System.out.println(ref5.draws);
        System.out.println(ref5.trophies);
        System.out.println(ref5.sponsor);
        System.out.println(ref5.jerseyColor);
        System.out.println(ref5.foundedYear);
        System.out.println(ref5.budget);
        System.out.println(ref5.fans);
		
		        Cricket ref6=new Cricket();
        ref6.teamName="NewZealand";
        ref6.captain="Williamson";
        ref6.coach="Stead";
        ref6.stadium="EdenPark";
        ref6.country="NewZealand";
        ref6.players=11;
        ref6.runs=240;
        ref6.wickets=7;
        ref6.overs=50;
        ref6.matchType="ODI";
        ref6.ranking=6;
        ref6.wins=5;
        ref6.losses=7;
        ref6.draws=0;
        ref6.trophies=2;
        ref6.sponsor="ANZ";
        ref6.jerseyColor="Black";
        ref6.foundedYear=1930;
        ref6.budget=360;
        ref6.fans=700000;

        System.out.println(ref6.teamName);
        System.out.println(ref6.captain);
        System.out.println(ref6.coach);
        System.out.println(ref6.stadium);
        System.out.println(ref6.country);
        System.out.println(ref6.players);
        System.out.println(ref6.runs);
        System.out.println(ref6.wickets);
        System.out.println(ref6.overs);
        System.out.println(ref6.matchType);
        System.out.println(ref6.ranking);
        System.out.println(ref6.wins);
        System.out.println(ref6.losses);
        System.out.println(ref6.draws);
        System.out.println(ref6.trophies);
        System.out.println(ref6.sponsor);
        System.out.println(ref6.jerseyColor);
        System.out.println(ref6.foundedYear);
        System.out.println(ref6.budget);
        System.out.println(ref6.fans);


        Cricket ref7=new Cricket();
        ref7.teamName="SriLanka";
        ref7.captain="Shanaka";
        ref7.coach="Silverwood";
        ref7.stadium="Colombo";
        ref7.country="SriLanka";
        ref7.players=11;
        ref7.runs=230;
        ref7.wickets=6;
        ref7.overs=50;
        ref7.matchType="ODI";
        ref7.ranking=7;
        ref7.wins=5;
        ref7.losses=7;
        ref7.draws=0;
        ref7.trophies=1;
        ref7.sponsor="Dialog";
        ref7.jerseyColor="Blue";
        ref7.foundedYear=1926;
        ref7.budget=340;
        ref7.fans=650000;

        System.out.println(ref7.teamName);
        System.out.println(ref7.captain);
        System.out.println(ref7.coach);
        System.out.println(ref7.stadium);
        System.out.println(ref7.country);
        System.out.println(ref7.players);
        System.out.println(ref7.runs);
        System.out.println(ref7.wickets);
        System.out.println(ref7.overs);
        System.out.println(ref7.matchType);
        System.out.println(ref7.ranking);
        System.out.println(ref7.wins);
        System.out.println(ref7.losses);
        System.out.println(ref7.draws);
        System.out.println(ref7.trophies);
        System.out.println(ref7.sponsor);
        System.out.println(ref7.jerseyColor);
        System.out.println(ref7.foundedYear);
        System.out.println(ref7.budget);
        System.out.println(ref7.fans);


        Cricket ref8=new Cricket();
        ref8.teamName="Bangladesh";
        ref8.captain="Shakib";
        ref8.coach="Hathurusingha";
        ref8.stadium="Dhaka";
        ref8.country="Bangladesh";
        ref8.players=11;
        ref8.runs=220;
        ref8.wickets=8;
        ref8.overs=50;
        ref8.matchType="ODI";
        ref8.ranking=8;
        ref8.wins=4;
        ref8.losses=8;
        ref8.draws=0;
        ref8.trophies=0;
        ref8.sponsor="Grameen";
        ref8.jerseyColor="Green";
        ref8.foundedYear=1972;
        ref8.budget=320;
        ref8.fans=600000;

        System.out.println(ref8.teamName);
        System.out.println(ref8.captain);
        System.out.println(ref8.coach);
        System.out.println(ref8.stadium);
        System.out.println(ref8.country);
        System.out.println(ref8.players);
        System.out.println(ref8.runs);
        System.out.println(ref8.wickets);
        System.out.println(ref8.overs);
        System.out.println(ref8.matchType);
        System.out.println(ref8.ranking);
        System.out.println(ref8.wins);
        System.out.println(ref8.losses);
        System.out.println(ref8.draws);
        System.out.println(ref8.trophies);
        System.out.println(ref8.sponsor);
        System.out.println(ref8.jerseyColor);
        System.out.println(ref8.foundedYear);
        System.out.println(ref8.budget);
        System.out.println(ref8.fans);


        Cricket ref9=new Cricket();
        ref9.teamName="WestIndies";
        ref9.captain="Holder";
        ref9.coach="Simmons";
        ref9.stadium="Barbados";
        ref9.country="WestIndies";
        ref9.players=11;
        ref9.runs=210;
        ref9.wickets=7;
        ref9.overs=50;
        ref9.matchType="ODI";
        ref9.ranking=9;
        ref9.wins=3;
        ref9.losses=9;
        ref9.draws=0;
        ref9.trophies=2;
        ref9.sponsor="Sandals";
        ref9.jerseyColor="Maroon";
        ref9.foundedYear=1928;
        ref9.budget=300;
        ref9.fans=550000;

        System.out.println(ref9.teamName);
        System.out.println(ref9.captain);
        System.out.println(ref9.coach);
        System.out.println(ref9.stadium);
        System.out.println(ref9.country);
        System.out.println(ref9.players);
        System.out.println(ref9.runs);
        System.out.println(ref9.wickets);
        System.out.println(ref9.overs);
        System.out.println(ref9.matchType);
        System.out.println(ref9.ranking);
        System.out.println(ref9.wins);
        System.out.println(ref9.losses);
        System.out.println(ref9.draws);
        System.out.println(ref9.trophies);
        System.out.println(ref9.sponsor);
        System.out.println(ref9.jerseyColor);
        System.out.println(ref9.foundedYear);
        System.out.println(ref9.budget);
        System.out.println(ref9.fans);


        Cricket ref10=new Cricket();
        ref10.teamName="Afghanistan";
        ref10.captain="Rashid";
        ref10.coach="Trott";
        ref10.stadium="Kabul";
        ref10.country="Afghanistan";
        ref10.players=11;
        ref10.runs=200;
        ref10.wickets=6;
        ref10.overs=50;
        ref10.matchType="ODI";
        ref10.ranking=10;
        ref10.wins=3;
        ref10.losses=9;
        ref10.draws=0;
        ref10.trophies=0;
        ref10.sponsor="Etisalat";
        ref10.jerseyColor="Blue";
        ref10.foundedYear=1995;
        ref10.budget=280;
        ref10.fans=500000;

        System.out.println(ref10.teamName);
        System.out.println(ref10.captain);
        System.out.println(ref10.coach);
        System.out.println(ref10.stadium);
        System.out.println(ref10.country);
        System.out.println(ref10.players);
        System.out.println(ref10.runs);
        System.out.println(ref10.wickets);
        System.out.println(ref10.overs);
        System.out.println(ref10.matchType);
        System.out.println(ref10.ranking);
        System.out.println(ref10.wins);
        System.out.println(ref10.losses);
        System.out.println(ref10.draws);
        System.out.println(ref10.trophies);
        System.out.println(ref10.sponsor);
        System.out.println(ref10.jerseyColor);
        System.out.println(ref10.foundedYear);
        System.out.println(ref10.budget);
        System.out.println(ref10.fans);
		
		        Cricket ref11=new Cricket();
        ref11.teamName="Ireland";
        ref11.captain="Balbirnie";
        ref11.coach="White";
        ref11.stadium="Dublin";
        ref11.country="Ireland";
        ref11.players=11;
        ref11.runs=195;
        ref11.wickets=7;
        ref11.overs=50;
        ref11.matchType="ODI";
        ref11.ranking=11;
        ref11.wins=2;
        ref11.losses=10;
        ref11.draws=0;
        ref11.trophies=0;
        ref11.sponsor="Guinness";
        ref11.jerseyColor="Green";
        ref11.foundedYear=1993;
        ref11.budget=250;
        ref11.fans=400000;

        System.out.println(ref11.teamName);
        System.out.println(ref11.captain);
        System.out.println(ref11.coach);
        System.out.println(ref11.stadium);
        System.out.println(ref11.country);
        System.out.println(ref11.players);
        System.out.println(ref11.runs);
        System.out.println(ref11.wickets);
        System.out.println(ref11.overs);
        System.out.println(ref11.matchType);
        System.out.println(ref11.ranking);
        System.out.println(ref11.wins);
        System.out.println(ref11.losses);
        System.out.println(ref11.draws);
        System.out.println(ref11.trophies);
        System.out.println(ref11.sponsor);
        System.out.println(ref11.jerseyColor);
        System.out.println(ref11.foundedYear);
        System.out.println(ref11.budget);
        System.out.println(ref11.fans);


        Cricket ref12=new Cricket();
        ref12.teamName="Zimbabwe";
        ref12.captain="Ervine";
        ref12.coach="Houghton";
        ref12.stadium="Harare";
        ref12.country="Zimbabwe";
        ref12.players=11;
        ref12.runs=190;
        ref12.wickets=6;
        ref12.overs=50;
        ref12.matchType="ODI";
        ref12.ranking=12;
        ref12.wins=2;
        ref12.losses=10;
        ref12.draws=0;
        ref12.trophies=0;
        ref12.sponsor="Castle";
        ref12.jerseyColor="Red";
        ref12.foundedYear=1992;
        ref12.budget=230;
        ref12.fans=350000;

        System.out.println(ref12.teamName);
        System.out.println(ref12.captain);
        System.out.println(ref12.coach);
        System.out.println(ref12.stadium);
        System.out.println(ref12.country);
        System.out.println(ref12.players);
        System.out.println(ref12.runs);
        System.out.println(ref12.wickets);
        System.out.println(ref12.overs);
        System.out.println(ref12.matchType);
        System.out.println(ref12.ranking);
        System.out.println(ref12.wins);
        System.out.println(ref12.losses);
        System.out.println(ref12.draws);
        System.out.println(ref12.trophies);
        System.out.println(ref12.sponsor);
        System.out.println(ref12.jerseyColor);
        System.out.println(ref12.foundedYear);
        System.out.println(ref12.budget);
        System.out.println(ref12.fans);


        Cricket ref13=new Cricket();
        ref13.teamName="Netherlands";
        ref13.captain="Edwards";
        ref13.coach="RyanCook";
        ref13.stadium="Amsterdam";
        ref13.country="Netherlands";
        ref13.players=11;
        ref13.runs=185;
        ref13.wickets=5;
        ref13.overs=50;
        ref13.matchType="ODI";
        ref13.ranking=13;
        ref13.wins=2;
        ref13.losses=10;
        ref13.draws=0;
        ref13.trophies=0;
        ref13.sponsor="Heineken";
        ref13.jerseyColor="Orange";
        ref13.foundedYear=1966;
        ref13.budget=210;
        ref13.fans=300000;

        System.out.println(ref13.teamName);
        System.out.println(ref13.captain);
        System.out.println(ref13.coach);
        System.out.println(ref13.stadium);
        System.out.println(ref13.country);
        System.out.println(ref13.players);
        System.out.println(ref13.runs);
        System.out.println(ref13.wickets);
        System.out.println(ref13.overs);
        System.out.println(ref13.matchType);
        System.out.println(ref13.ranking);
        System.out.println(ref13.wins);
        System.out.println(ref13.losses);
        System.out.println(ref13.draws);
        System.out.println(ref13.trophies);
        System.out.println(ref13.sponsor);
        System.out.println(ref13.jerseyColor);
        System.out.println(ref13.foundedYear);
        System.out.println(ref13.budget);
        System.out.println(ref13.fans);


        Cricket ref14=new Cricket();
        ref14.teamName="Nepal";
        ref14.captain="RohitPaudel";
        ref14.coach="Pubudu";
        ref14.stadium="Kathmandu";
        ref14.country="Nepal";
        ref14.players=11;
        ref14.runs=180;
        ref14.wickets=5;
        ref14.overs=50;
        ref14.matchType="ODI";
        ref14.ranking=14;
        ref14.wins=1;
        ref14.losses=11;
        ref14.draws=0;
        ref14.trophies=0;
        ref14.sponsor="Yeti";
        ref14.jerseyColor="Blue";
        ref14.foundedYear=1996;
        ref14.budget=200;
        ref14.fans=250000;

        System.out.println(ref14.teamName);
        System.out.println(ref14.captain);
        System.out.println(ref14.coach);
        System.out.println(ref14.stadium);
        System.out.println(ref14.country);
        System.out.println(ref14.players);
        System.out.println(ref14.runs);
        System.out.println(ref14.wickets);
        System.out.println(ref14.overs);
        System.out.println(ref14.matchType);
        System.out.println(ref14.ranking);
        System.out.println(ref14.wins);
        System.out.println(ref14.losses);
        System.out.println(ref14.draws);
        System.out.println(ref14.trophies);
        System.out.println(ref14.sponsor);
        System.out.println(ref14.jerseyColor);
        System.out.println(ref14.foundedYear);
        System.out.println(ref14.budget);
        System.out.println(ref14.fans);


        Cricket ref15=new Cricket();
        ref15.teamName="Canada";
        ref15.captain="SaadBinZafar";
        ref15.coach="DavWhatmore";
        ref15.stadium="Toronto";
        ref15.country="Canada";
        ref15.players=11;
        ref15.runs=175;
        ref15.wickets=4;
        ref15.overs=50;
        ref15.matchType="ODI";
        ref15.ranking=15;
        ref15.wins=1;
        ref15.losses=11;
        ref15.draws=0;
        ref15.trophies=0;
        ref15.sponsor="TimHortons";
        ref15.jerseyColor="Red";
        ref15.foundedYear=1968;
        ref15.budget=180;
        ref15.fans=200000;

        System.out.println(ref15.teamName);
        System.out.println(ref15.captain);
        System.out.println(ref15.coach);
        System.out.println(ref15.stadium);
        System.out.println(ref15.country);
        System.out.println(ref15.players);
        System.out.println(ref15.runs);
        System.out.println(ref15.wickets);
        System.out.println(ref15.overs);
        System.out.println(ref15.matchType);
        System.out.println(ref15.ranking);
        System.out.println(ref15.wins);
        System.out.println(ref15.losses);
        System.out.println(ref15.draws);
        System.out.println(ref15.trophies);
        System.out.println(ref15.sponsor);
        System.out.println(ref15.jerseyColor);
        System.out.println(ref15.foundedYear);
        System.out.println(ref15.budget);
        System.out.println(ref15.fans);
		
		        Cricket ref16=new Cricket();
        ref16.teamName="Scotland";
        ref16.captain="Berrington";
        ref16.coach="ShaneBurger";
        ref16.stadium="Edinburgh";
        ref16.country="Scotland";
        ref16.players=11;
        ref16.runs=170;
        ref16.wickets=6;
        ref16.overs=50;
        ref16.matchType="ODI";
        ref16.ranking=16;
        ref16.wins=1;
        ref16.losses=11;
        ref16.draws=0;
        ref16.trophies=0;
        ref16.sponsor="Saltire";
        ref16.jerseyColor="Purple";
        ref16.foundedYear=1994;
        ref16.budget=170;
        ref16.fans=180000;

        System.out.println(ref16.teamName);
        System.out.println(ref16.captain);
        System.out.println(ref16.coach);
        System.out.println(ref16.stadium);
        System.out.println(ref16.country);
        System.out.println(ref16.players);
        System.out.println(ref16.runs);
        System.out.println(ref16.wickets);
        System.out.println(ref16.overs);
        System.out.println(ref16.matchType);
        System.out.println(ref16.ranking);
        System.out.println(ref16.wins);
        System.out.println(ref16.losses);
        System.out.println(ref16.draws);
        System.out.println(ref16.trophies);
        System.out.println(ref16.sponsor);
        System.out.println(ref16.jerseyColor);
        System.out.println(ref16.foundedYear);
        System.out.println(ref16.budget);
        System.out.println(ref16.fans);


        Cricket ref17=new Cricket();
        ref17.teamName="UAE";
        ref17.captain="MuhammadWaseem";
        ref17.coach="RobinSingh";
        ref17.stadium="Dubai";
        ref17.country="UAE";
        ref17.players=11;
        ref17.runs=168;
        ref17.wickets=5;
        ref17.overs=50;
        ref17.matchType="ODI";
        ref17.ranking=17;
        ref17.wins=1;
        ref17.losses=11;
        ref17.draws=0;
        ref17.trophies=0;
        ref17.sponsor="Emirates";
        ref17.jerseyColor="Red";
        ref17.foundedYear=1989;
        ref17.budget=160;
        ref17.fans=170000;

        System.out.println(ref17.teamName);
        System.out.println(ref17.captain);
        System.out.println(ref17.coach);
        System.out.println(ref17.stadium);
        System.out.println(ref17.country);
        System.out.println(ref17.players);
        System.out.println(ref17.runs);
        System.out.println(ref17.wickets);
        System.out.println(ref17.overs);
        System.out.println(ref17.matchType);
        System.out.println(ref17.ranking);
        System.out.println(ref17.wins);
        System.out.println(ref17.losses);
        System.out.println(ref17.draws);
        System.out.println(ref17.trophies);
        System.out.println(ref17.sponsor);
        System.out.println(ref17.jerseyColor);
        System.out.println(ref17.foundedYear);
        System.out.println(ref17.budget);
        System.out.println(ref17.fans);


        Cricket ref18=new Cricket();
        ref18.teamName="Oman";
        ref18.captain="ZeeshanMaqsood";
        ref18.coach="DuleepMendis";
        ref18.stadium="Muscat";
        ref18.country="Oman";
        ref18.players=11;
        ref18.runs=165;
        ref18.wickets=5;
        ref18.overs=50;
        ref18.matchType="ODI";
        ref18.ranking=18;
        ref18.wins=1;
        ref18.losses=11;
        ref18.draws=0;
        ref18.trophies=0;
        ref18.sponsor="OmanAir";
        ref18.jerseyColor="Red";
        ref18.foundedYear=1979;
        ref18.budget=150;
        ref18.fans=150000;

        System.out.println(ref18.teamName);
        System.out.println(ref18.captain);
        System.out.println(ref18.coach);
        System.out.println(ref18.stadium);
        System.out.println(ref18.country);
        System.out.println(ref18.players);
        System.out.println(ref18.runs);
        System.out.println(ref18.wickets);
        System.out.println(ref18.overs);
        System.out.println(ref18.matchType);
        System.out.println(ref18.ranking);
        System.out.println(ref18.wins);
        System.out.println(ref18.losses);
        System.out.println(ref18.draws);
        System.out.println(ref18.trophies);
        System.out.println(ref18.sponsor);
        System.out.println(ref18.jerseyColor);
        System.out.println(ref18.foundedYear);
        System.out.println(ref18.budget);
        System.out.println(ref18.fans);


        Cricket ref19=new Cricket();
        ref19.teamName="Namibia";
        ref19.captain="GerhardErasmus";
        ref19.coach="PierreDeBruyn";
        ref19.stadium="Windhoek";
        ref19.country="Namibia";
        ref19.players=11;
        ref19.runs=160;
        ref19.wickets=4;
        ref19.overs=50;
        ref19.matchType="ODI";
        ref19.ranking=19;
        ref19.wins=1;
        ref19.losses=11;
        ref19.draws=0;
        ref19.trophies=0;
        ref19.sponsor="CastleLite";
        ref19.jerseyColor="Blue";
        ref19.foundedYear=1990;
        ref19.budget=140;
        ref19.fans=140000;

        System.out.println(ref19.teamName);
        System.out.println(ref19.captain);
        System.out.println(ref19.coach);
        System.out.println(ref19.stadium);
        System.out.println(ref19.country);
        System.out.println(ref19.players);
        System.out.println(ref19.runs);
        System.out.println(ref19.wickets);
        System.out.println(ref19.overs);
        System.out.println(ref19.matchType);
        System.out.println(ref19.ranking);
        System.out.println(ref19.wins);
        System.out.println(ref19.losses);
        System.out.println(ref19.draws);
        System.out.println(ref19.trophies);
        System.out.println(ref19.sponsor);
        System.out.println(ref19.jerseyColor);
        System.out.println(ref19.foundedYear);
        System.out.println(ref19.budget);
        System.out.println(ref19.fans);


        Cricket ref20=new Cricket();
        ref20.teamName="USA";
        ref20.captain="MonankPatel";
        ref20.coach="StuartLaw";
        ref20.stadium="Florida";
        ref20.country="USA";
        ref20.players=11;
        ref20.runs=158;
        ref20.wickets=4;
        ref20.overs=50;
        ref20.matchType="ODI";
        ref20.ranking=20;
        ref20.wins=1;
        ref20.losses=11;
        ref20.draws=0;
        ref20.trophies=0;
        ref20.sponsor="Pepsi";
        ref20.jerseyColor="Blue";
        ref20.foundedYear=1965;
        ref20.budget=130;
        ref20.fans=130000;

        System.out.println(ref20.teamName);
        System.out.println(ref20.captain);
        System.out.println(ref20.coach);
        System.out.println(ref20.stadium);
        System.out.println(ref20.country);
        System.out.println(ref20.players);
        System.out.println(ref20.runs);
        System.out.println(ref20.wickets);
        System.out.println(ref20.overs);
        System.out.println(ref20.matchType);
        System.out.println(ref20.ranking);
        System.out.println(ref20.wins);
        System.out.println(ref20.losses);
        System.out.println(ref20.draws);
        System.out.println(ref20.trophies);
        System.out.println(ref20.sponsor);
        System.out.println(ref20.jerseyColor);
        System.out.println(ref20.foundedYear);
        System.out.println(ref20.budget);
        System.out.println(ref20.fans);
		
		System.out.println(" Parameterized Constructor Objects ");

Cricket p1=new Cricket("India","Rohit","Dravid","Wankhede","India",11,300,8,50,"ODI",1,10,2,0,5,"Dream11","Blue",1928,500,1000000);
System.out.println(p1.teamName);
System.out.println(p1.captain);
System.out.println(p1.coach);
System.out.println(p1.stadium);
System.out.println(p1.country);
System.out.println(p1.players);
System.out.println(p1.runs);
System.out.println(p1.wickets);
System.out.println(p1.overs);
System.out.println(p1.matchType);
System.out.println(p1.ranking);
System.out.println(p1.wins);
System.out.println(p1.losses);
System.out.println(p1.draws);
System.out.println(p1.trophies);
System.out.println(p1.sponsor);
System.out.println(p1.jerseyColor);
System.out.println(p1.foundedYear);
System.out.println(p1.budget);
System.out.println(p1.fans);


Cricket p2=new Cricket("Australia","Cummins","McDonald","MCG","Australia",11,280,7,50,"ODI",2,9,3,0,6,"Qantas","Yellow",1905,450,900000);
System.out.println(p2.teamName);
System.out.println(p2.captain);
System.out.println(p2.coach);
System.out.println(p2.stadium);
System.out.println(p2.country);
System.out.println(p2.players);
System.out.println(p2.runs);
System.out.println(p2.wickets);
System.out.println(p2.overs);
System.out.println(p2.matchType);
System.out.println(p2.ranking);
System.out.println(p2.wins);
System.out.println(p2.losses);
System.out.println(p2.draws);
System.out.println(p2.trophies);
System.out.println(p2.sponsor);
System.out.println(p2.jerseyColor);
System.out.println(p2.foundedYear);
System.out.println(p2.budget);
System.out.println(p2.fans);


Cricket p3=new Cricket("England","Buttler","Mott","Lords","England",11,270,6,50,"ODI",3,8,4,0,3,"Natwest","Blue",1877,430,850000);
System.out.println(p3.teamName);
System.out.println(p3.captain);
System.out.println(p3.coach);
System.out.println(p3.stadium);
System.out.println(p3.country);
System.out.println(p3.players);
System.out.println(p3.runs);
System.out.println(p3.wickets);
System.out.println(p3.overs);
System.out.println(p3.matchType);
System.out.println(p3.ranking);
System.out.println(p3.wins);
System.out.println(p3.losses);
System.out.println(p3.draws);
System.out.println(p3.trophies);
System.out.println(p3.sponsor);
System.out.println(p3.jerseyColor);
System.out.println(p3.foundedYear);
System.out.println(p3.budget);
System.out.println(p3.fans);


Cricket p4=new Cricket("Pakistan","Babar","Bradburn","Gaddafi","Pakistan",11,260,9,50,"ODI",4,7,5,0,2,"Pepsi","Green",1952,410,800000);
System.out.println(p4.teamName);
System.out.println(p4.captain);
System.out.println(p4.coach);
System.out.println(p4.stadium);
System.out.println(p4.country);
System.out.println(p4.players);
System.out.println(p4.runs);
System.out.println(p4.wickets);
System.out.println(p4.overs);
System.out.println(p4.matchType);
System.out.println(p4.ranking);
System.out.println(p4.wins);
System.out.println(p4.losses);
System.out.println(p4.draws);
System.out.println(p4.trophies);
System.out.println(p4.sponsor);
System.out.println(p4.jerseyColor);
System.out.println(p4.foundedYear);
System.out.println(p4.budget);
System.out.println(p4.fans);


Cricket p5=new Cricket("SouthAfrica","Markram","Boucher","Newlands","SouthAfrica",11,250,8,50,"ODI",5,6,6,0,1,"Castle","Green",1889,390,750000);
System.out.println(p5.teamName);
System.out.println(p5.captain);
System.out.println(p5.coach);
System.out.println(p5.stadium);
System.out.println(p5.country);
System.out.println(p5.players);
System.out.println(p5.runs);
System.out.println(p5.wickets);
System.out.println(p5.overs);
System.out.println(p5.matchType);
System.out.println(p5.ranking);
System.out.println(p5.wins);
System.out.println(p5.losses);
System.out.println(p5.draws);
System.out.println(p5.trophies);
System.out.println(p5.sponsor);
System.out.println(p5.jerseyColor);
System.out.println(p5.foundedYear);
System.out.println(p5.budget);
System.out.println(p5.fans);

Cricket p6=new Cricket("NewZealand","Williamson","Stead","EdenPark","NewZealand",11,240,7,50,"ODI",6,5,7,0,2,"ANZ","Black",1930,360,700000);
System.out.println(p6.teamName);
System.out.println(p6.captain);
System.out.println(p6.coach);
System.out.println(p6.stadium);
System.out.println(p6.country);
System.out.println(p6.players);
System.out.println(p6.runs);
System.out.println(p6.wickets);
System.out.println(p6.overs);
System.out.println(p6.matchType);
System.out.println(p6.ranking);
System.out.println(p6.wins);
System.out.println(p6.losses);
System.out.println(p6.draws);
System.out.println(p6.trophies);
System.out.println(p6.sponsor);
System.out.println(p6.jerseyColor);
System.out.println(p6.foundedYear);
System.out.println(p6.budget);
System.out.println(p6.fans);


Cricket p7=new Cricket("SriLanka","Shanaka","Silverwood","Colombo","SriLanka",11,230,6,50,"ODI",7,5,7,0,1,"Dialog","Blue",1926,340,650000);
System.out.println(p7.teamName);
System.out.println(p7.captain);
System.out.println(p7.coach);
System.out.println(p7.stadium);
System.out.println(p7.country);
System.out.println(p7.players);
System.out.println(p7.runs);
System.out.println(p7.wickets);
System.out.println(p7.overs);
System.out.println(p7.matchType);
System.out.println(p7.ranking);
System.out.println(p7.wins);
System.out.println(p7.losses);
System.out.println(p7.draws);
System.out.println(p7.trophies);
System.out.println(p7.sponsor);
System.out.println(p7.jerseyColor);
System.out.println(p7.foundedYear);
System.out.println(p7.budget);
System.out.println(p7.fans);


Cricket p8=new Cricket("Bangladesh","Shakib","Hathurusingha","Dhaka","Bangladesh",11,220,8,50,"ODI",8,4,8,0,0,"Grameen","Green",1972,320,600000);
System.out.println(p8.teamName);
System.out.println(p8.captain);
System.out.println(p8.coach);
System.out.println(p8.stadium);
System.out.println(p8.country);
System.out.println(p8.players);
System.out.println(p8.runs);
System.out.println(p8.wickets);
System.out.println(p8.overs);
System.out.println(p8.matchType);
System.out.println(p8.ranking);
System.out.println(p8.wins);
System.out.println(p8.losses);
System.out.println(p8.draws);
System.out.println(p8.trophies);
System.out.println(p8.sponsor);
System.out.println(p8.jerseyColor);
System.out.println(p8.foundedYear);
System.out.println(p8.budget);
System.out.println(p8.fans);


Cricket p9=new Cricket("WestIndies","Holder","Simmons","Barbados","WestIndies",11,210,7,50,"ODI",9,3,9,0,2,"Sandals","Maroon",1928,300,550000);
System.out.println(p9.teamName);
System.out.println(p9.captain);
System.out.println(p9.coach);
System.out.println(p9.stadium);
System.out.println(p9.country);
System.out.println(p9.players);
System.out.println(p9.runs);
System.out.println(p9.wickets);
System.out.println(p9.overs);
System.out.println(p9.matchType);
System.out.println(p9.ranking);
System.out.println(p9.wins);
System.out.println(p9.losses);
System.out.println(p9.draws);
System.out.println(p9.trophies);
System.out.println(p9.sponsor);
System.out.println(p9.jerseyColor);
System.out.println(p9.foundedYear);
System.out.println(p9.budget);
System.out.println(p9.fans);


Cricket p10=new Cricket("Afghanistan","Rashid","Trott","Kabul","Afghanistan",11,200,6,50,"ODI",10,3,9,0,0,"Etisalat","Blue",1995,280,500000);
System.out.println(p10.teamName);
System.out.println(p10.captain);
System.out.println(p10.coach);
System.out.println(p10.stadium);
System.out.println(p10.country);
System.out.println(p10.players);
System.out.println(p10.runs);
System.out.println(p10.wickets);
System.out.println(p10.overs);
System.out.println(p10.matchType);
System.out.println(p10.ranking);
System.out.println(p10.wins);
System.out.println(p10.losses);
System.out.println(p10.draws);
System.out.println(p10.trophies);
System.out.println(p10.sponsor);
System.out.println(p10.jerseyColor);
System.out.println(p10.foundedYear);
System.out.println(p10.budget);
System.out.println(p10.fans);

Cricket p11=new Cricket("Ireland","Balbirnie","White","Dublin","Ireland",11,195,7,50,"ODI",11,2,10,0,0,"Guinness","Green",1993,250,400000);
System.out.println(p11.teamName);
System.out.println(p11.captain);
System.out.println(p11.coach);
System.out.println(p11.stadium);
System.out.println(p11.country);
System.out.println(p11.players);
System.out.println(p11.runs);
System.out.println(p11.wickets);
System.out.println(p11.overs);
System.out.println(p11.matchType);
System.out.println(p11.ranking);
System.out.println(p11.wins);
System.out.println(p11.losses);
System.out.println(p11.draws);
System.out.println(p11.trophies);
System.out.println(p11.sponsor);
System.out.println(p11.jerseyColor);
System.out.println(p11.foundedYear);
System.out.println(p11.budget);
System.out.println(p11.fans);


Cricket p12=new Cricket("Zimbabwe","Ervine","Houghton","Harare","Zimbabwe",11,190,6,50,"ODI",12,2,10,0,0,"Castle","Red",1992,230,350000);
System.out.println(p12.teamName);
System.out.println(p12.captain);
System.out.println(p12.coach);
System.out.println(p12.stadium);
System.out.println(p12.country);
System.out.println(p12.players);
System.out.println(p12.runs);
System.out.println(p12.wickets);
System.out.println(p12.overs);
System.out.println(p12.matchType);
System.out.println(p12.ranking);
System.out.println(p12.wins);
System.out.println(p12.losses);
System.out.println(p12.draws);
System.out.println(p12.trophies);
System.out.println(p12.sponsor);
System.out.println(p12.jerseyColor);
System.out.println(p12.foundedYear);
System.out.println(p12.budget);
System.out.println(p12.fans);


Cricket p13=new Cricket("Netherlands","Edwards","RyanCook","Amsterdam","Netherlands",11,185,5,50,"ODI",13,2,10,0,0,"Heineken","Orange",1966,210,300000);
System.out.println(p13.teamName);
System.out.println(p13.captain);
System.out.println(p13.coach);
System.out.println(p13.stadium);
System.out.println(p13.country);
System.out.println(p13.players);
System.out.println(p13.runs);
System.out.println(p13.wickets);
System.out.println(p13.overs);
System.out.println(p13.matchType);
System.out.println(p13.ranking);
System.out.println(p13.wins);
System.out.println(p13.losses);
System.out.println(p13.draws);
System.out.println(p13.trophies);
System.out.println(p13.sponsor);
System.out.println(p13.jerseyColor);
System.out.println(p13.foundedYear);
System.out.println(p13.budget);
System.out.println(p13.fans);


Cricket p14=new Cricket("Nepal","RohitPaudel","Pubudu","Kathmandu","Nepal",11,180,5,50,"ODI",14,1,11,0,0,"Yeti","Blue",1996,200,250000);
System.out.println(p14.teamName);
System.out.println(p14.captain);
System.out.println(p14.coach);
System.out.println(p14.stadium);
System.out.println(p14.country);
System.out.println(p14.players);
System.out.println(p14.runs);
System.out.println(p14.wickets);
System.out.println(p14.overs);
System.out.println(p14.matchType);
System.out.println(p14.ranking);
System.out.println(p14.wins);
System.out.println(p14.losses);
System.out.println(p14.draws);
System.out.println(p14.trophies);
System.out.println(p14.sponsor);
System.out.println(p14.jerseyColor);
System.out.println(p14.foundedYear);
System.out.println(p14.budget);
System.out.println(p14.fans);


Cricket p15=new Cricket("Canada","SaadBinZafar","DavWhatmore","Toronto","Canada",11,175,4,50,"ODI",15,1,11,0,0,"TimHortons","Red",1968,180,200000);
System.out.println(p15.teamName);
System.out.println(p15.captain);
System.out.println(p15.coach);
System.out.println(p15.stadium);
System.out.println(p15.country);
System.out.println(p15.players);
System.out.println(p15.runs);
System.out.println(p15.wickets);
System.out.println(p15.overs);
System.out.println(p15.matchType);
System.out.println(p15.ranking);
System.out.println(p15.wins);
System.out.println(p15.losses);
System.out.println(p15.draws);
System.out.println(p15.trophies);
System.out.println(p15.sponsor);
System.out.println(p15.jerseyColor);
System.out.println(p15.foundedYear);
System.out.println(p15.budget);
System.out.println(p15.fans);

Cricket p16=new Cricket("Scotland","Berrington","ShaneBurger","Edinburgh","Scotland",11,170,6,50,"ODI",16,1,11,0,0,"Saltire","Purple",1994,170,180000);
System.out.println(p16.teamName);
System.out.println(p16.captain);
System.out.println(p16.coach);
System.out.println(p16.stadium);
System.out.println(p16.country);
System.out.println(p16.players);
System.out.println(p16.runs);
System.out.println(p16.wickets);
System.out.println(p16.overs);
System.out.println(p16.matchType);
System.out.println(p16.ranking);
System.out.println(p16.wins);
System.out.println(p16.losses);
System.out.println(p16.draws);
System.out.println(p16.trophies);
System.out.println(p16.sponsor);
System.out.println(p16.jerseyColor);
System.out.println(p16.foundedYear);
System.out.println(p16.budget);
System.out.println(p16.fans);


Cricket p17=new Cricket("UAE","MuhammadWaseem","RobinSingh","Dubai","UAE",11,168,5,50,"ODI",17,1,11,0,0,"Emirates","Red",1989,160,170000);
System.out.println(p17.teamName);
System.out.println(p17.captain);
System.out.println(p17.coach);
System.out.println(p17.stadium);
System.out.println(p17.country);
System.out.println(p17.players);
System.out.println(p17.runs);
System.out.println(p17.wickets);
System.out.println(p17.overs);
System.out.println(p17.matchType);
System.out.println(p17.ranking);
System.out.println(p17.wins);
System.out.println(p17.losses);
System.out.println(p17.draws);
System.out.println(p17.trophies);
System.out.println(p17.sponsor);
System.out.println(p17.jerseyColor);
System.out.println(p17.foundedYear);
System.out.println(p17.budget);
System.out.println(p17.fans);


Cricket p18=new Cricket("Oman","ZeeshanMaqsood","DuleepMendis","Muscat","Oman",11,165,5,50,"ODI",18,1,11,0,0,"OmanAir","Red",1979,150,150000);
System.out.println(p18.teamName);
System.out.println(p18.captain);
System.out.println(p18.coach);
System.out.println(p18.stadium);
System.out.println(p18.country);
System.out.println(p18.players);
System.out.println(p18.runs);
System.out.println(p18.wickets);
System.out.println(p18.overs);
System.out.println(p18.matchType);
System.out.println(p18.ranking);
System.out.println(p18.wins);
System.out.println(p18.losses);
System.out.println(p18.draws);
System.out.println(p18.trophies);
System.out.println(p18.sponsor);
System.out.println(p18.jerseyColor);
System.out.println(p18.foundedYear);
System.out.println(p18.budget);
System.out.println(p18.fans);


Cricket p19=new Cricket("Namibia","GerhardErasmus","PierreDeBruyn","Windhoek","Namibia",11,160,4,50,"ODI",19,1,11,0,0,"CastleLite","Blue",1990,140,140000);
System.out.println(p19.teamName);
System.out.println(p19.captain);
System.out.println(p19.coach);
System.out.println(p19.stadium);
System.out.println(p19.country);
System.out.println(p19.players);
System.out.println(p19.runs);
System.out.println(p19.wickets);
System.out.println(p19.overs);
System.out.println(p19.matchType);
System.out.println(p19.ranking);
System.out.println(p19.wins);
System.out.println(p19.losses);
System.out.println(p19.draws);
System.out.println(p19.trophies);
System.out.println(p19.sponsor);
System.out.println(p19.jerseyColor);
System.out.println(p19.foundedYear);
System.out.println(p19.budget);
System.out.println(p19.fans);


Cricket p20=new Cricket("USA","MonankPatel","StuartLaw","Florida","USA",11,158,4,50,"ODI",20,1,11,0,0,"Pepsi","Blue",1965,130,130000);
System.out.println(p20.teamName);
System.out.println(p20.captain);
System.out.println(p20.coach);
System.out.println(p20.stadium);
System.out.println(p20.country);
System.out.println(p20.players);
System.out.println(p20.runs);
System.out.println(p20.wickets);
System.out.println(p20.overs);
System.out.println(p20.matchType);
System.out.println(p20.ranking);
System.out.println(p20.wins);
System.out.println(p20.losses);
System.out.println(p20.draws);
System.out.println(p20.trophies);
System.out.println(p20.sponsor);
System.out.println(p20.jerseyColor);
System.out.println(p20.foundedYear);
System.out.println(p20.budget);
System.out.println(p20.fans);

Cricket p21=new Cricket("Kenya","Tikolo","Odoyo","Nairobi","Kenya",11,155,4,50,"ODI",21,1,11,0,0,"Safari","Green",1960,120,120000);
System.out.println(p21.teamName);
System.out.println(p21.captain);
System.out.println(p21.coach);
System.out.println(p21.stadium);
System.out.println(p21.country);
System.out.println(p21.players);
System.out.println(p21.runs);
System.out.println(p21.wickets);
System.out.println(p21.overs);
System.out.println(p21.matchType);
System.out.println(p21.ranking);
System.out.println(p21.wins);
System.out.println(p21.losses);
System.out.println(p21.draws);
System.out.println(p21.trophies);
System.out.println(p21.sponsor);
System.out.println(p21.jerseyColor);
System.out.println(p21.foundedYear);
System.out.println(p21.budget);
System.out.println(p21.fans);


Cricket p22=new Cricket("HongKong","Nizakat","Aftab","HongKong","HongKong",11,150,3,50,"ODI",22,1,11,0,0,"Cathay","Red",1950,110,110000);
System.out.println(p22.teamName);
System.out.println(p22.captain);
System.out.println(p22.coach);
System.out.println(p22.stadium);
System.out.println(p22.country);
System.out.println(p22.players);
System.out.println(p22.runs);
System.out.println(p22.wickets);
System.out.println(p22.overs);
System.out.println(p22.matchType);
System.out.println(p22.ranking);
System.out.println(p22.wins);
System.out.println(p22.losses);
System.out.println(p22.draws);
System.out.println(p22.trophies);
System.out.println(p22.sponsor);
System.out.println(p22.jerseyColor);
System.out.println(p22.foundedYear);
System.out.println(p22.budget);
System.out.println(p22.fans);


Cricket p23=new Cricket("Malaysia","AhmadFaiz","Arul","KualaLumpur","Malaysia",11,148,3,50,"ODI",23,1,11,0,0,"Petronas","Blue",1970,100,100000);
System.out.println(p23.teamName);
System.out.println(p23.captain);
System.out.println(p23.coach);
System.out.println(p23.stadium);
System.out.println(p23.country);
System.out.println(p23.players);
System.out.println(p23.runs);
System.out.println(p23.wickets);
System.out.println(p23.overs);
System.out.println(p23.matchType);
System.out.println(p23.ranking);
System.out.println(p23.wins);
System.out.println(p23.losses);
System.out.println(p23.draws);
System.out.println(p23.trophies);
System.out.println(p23.sponsor);
System.out.println(p23.jerseyColor);
System.out.println(p23.foundedYear);
System.out.println(p23.budget);
System.out.println(p23.fans);


Cricket p24=new Cricket("Singapore","TimDavid","Monty","Singapore","Singapore",11,145,3,50,"ODI",24,1,11,0,0,"Tiger","Red",1965,95000,95000);
System.out.println(p24.teamName);
System.out.println(p24.captain);
System.out.println(p24.coach);
System.out.println(p24.stadium);
System.out.println(p24.country);
System.out.println(p24.players);
System.out.println(p24.runs);
System.out.println(p24.wickets);
System.out.println(p24.overs);
System.out.println(p24.matchType);
System.out.println(p24.ranking);
System.out.println(p24.wins);
System.out.println(p24.losses);
System.out.println(p24.draws);
System.out.println(p24.trophies);
System.out.println(p24.sponsor);
System.out.println(p24.jerseyColor);
System.out.println(p24.foundedYear);
System.out.println(p24.budget);
System.out.println(p24.fans);


Cricket p25=new Cricket("Thailand","Chantham","Harper","Bangkok","Thailand",11,140,3,50,"ODI",25,1,11,0,0,"Chang","Blue",1990,90000,90000);
System.out.println(p25.teamName);
System.out.println(p25.captain);
System.out.println(p25.coach);
System.out.println(p25.stadium);
System.out.println(p25.country);
System.out.println(p25.players);
System.out.println(p25.runs);
System.out.println(p25.wickets);
System.out.println(p25.overs);
System.out.println(p25.matchType);
System.out.println(p25.ranking);
System.out.println(p25.wins);
System.out.println(p25.losses);
System.out.println(p25.draws);
System.out.println(p25.trophies);
System.out.println(p25.sponsor);
System.out.println(p25.jerseyColor);
System.out.println(p25.foundedYear);
System.out.println(p25.budget);
System.out.println(p25.fans);
		
		

    }
}